// ─── Site Configuration ───────────────────────────────────────────────────────

export const siteConfig = {
  name:        "Al Yasmine Center",
  nameAr:      "مركز الياسمين",
  tagline:     "Grow. Transform. Bloom.",
  taglineAr:   "انمُ. تحوّل. تفتّح.",
  description: "Transformative coaching and personal development programs designed to help you unlock your fullest potential.",
  url:         "https://alyasminecenter.com",
  email:       "alyasmine.center@gmail.com",
  phone:       "+971 52 441 7078",
  // WhatsApp number in international format, digits only (used for wa.me links)
  whatsapp:    "971524417078",
  instagram:   "https://instagram.com/Alyasmine_center",

  // TODO: Replace with your real Calendly link when ready
  // e.g. "https://calendly.com/aliyah-albahari/discovery-call"
  calendlyUrl: "",

  // Coach — update photo URL when real one is available
  coachName:   "Alia AlBahri",
  coachNameAr: "علياء البحري",
  coachTitle:  "CBT Specialist & Certified Life Coach",
  // TODO: Add full bio when client provides it
  coachBio:    "Alia AlBahri is a Cognitive Behavioural Therapy specialist and certified life coach dedicated to guiding women through meaningful, lasting transformation. Her evidence-based approach creates a safe, nurturing space where real change becomes possible.",
  // TODO: Replace with real photo
  coachPhoto:  "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80",
} as const;

// ─── Navigation ───────────────────────────────────────────────────────────────

export const navLinks = [
  { label: "Home",        href: "/"            },
  { label: "About",       href: "/about"       },
  { label: "Services",    href: "/services"    },
  { label: "Proof",       href: "/proof"       },
  { label: "Pricing",     href: "/pricing"     },
  { label: "Book Now",    href: "/booking", isButton: true },
] as const;

// ─── Brand Colors ─────────────────────────────────────────────────────────────

export const brandColors = {
  gold:      "#ECA200",
  cream:     "#F6F2E9",
  teal:      "#035A60",
  tealLight: "#7FB0B4",
  charcoal:  "#252525",
  dark:      "#2F2F2F",
  blush:     "#F2C4B5",
} as const;

// ─── Services ─────────────────────────────────────────────────────────────────

export const services = [
  {
    id:          "consultation",
    title:       "Psychological Consultation & Guidance",
    titleAr:     "الاستشارة والإرشاد النفسي",
    description: "A first consultation & guidance session focused on identifying your concern and building the right action plan together. The essential first step before any therapeutic journey.",
    descriptionAr: "جلسة استشارة وإرشاد أولى تركّز على فهم وضعك وبناء خطة عمل مناسبة. الخطوة الأساسية قبل أي رحلة علاجية.",
    includes: [
      "Initial assessment of your concern",
      "Professional guidance from Alia",
      "A personalised action plan for next steps",
    ],
    includesAr: [
      "تقييم أولي لما تمرّين به",
      "إرشاد مهني من علياء",
      "خطة عمل مخصّصة للخطوات التالية",
    ],
    format:      "Online via Zoom",
    formatAr:    "أونلاين عبر زوم",
    duration:    "90 min",
    durationAr:  "90 دقيقة",
    price:       null,
    priceNote:   "Urgent consultation & guidance available, contact us.",
    priceNoteAr: "تتوفر استشارة وإرشاد عاجلة، تواصلي معنا.",
    icon:        "✦",
    image:       "/services/consultation.png",
    timeline: [
      { en: "Share your story in a safe, private space", ar: "شاركي قصتك في مساحة آمنة وخاصة" },
      { en: "Alia listens deeply to understand your situation", ar: "تستمع علياء بعمق لفهم وضعك" },
      { en: "Identify the core concern together", ar: "تحديد المشكلة الأساسية معاً" },
      { en: "Receive a personalised action plan", ar: "الحصول على خطة عمل مخصصة لكِ" },
      { en: "Leave with clarity and next steps", ar: "الخروج بوضوح وخطوات واضحة للأمام" },
    ],
  },
  {
    id:          "cbt-sessions",
    title:       "Psychological Counseling & CBT Sessions",
    titleAr:     "جلسات الإرشاد النفسي والعلاج السلوكي المعرفي",
    description: "Follow-up sessions designed to apply the action plan agreed in your initial consultation & guidance. This is where real, lasting change takes root.",
    descriptionAr: "جلسات متابعة لتطبيق خطة العمل المتفق عليها في الاستشارة والإرشاد الأولى. هنا يبدأ التغيير الحقيقي والعميق.",
    includes: [
      "Ongoing therapeutic support",
      "Application of your personalised treatment plan",
      "Sessions with Alia AlBahri",
    ],
    includesAr: [
      "دعم علاجي مستمر",
      "تطبيق خطة العلاج المخصّصة لكِ",
      "جلسات مع علياء البحري",
    ],
    format:      "Session-based",
    formatAr:    "بالجلسة",
    duration:    "50 min per session",
    durationAr:  "50 دقيقة لكل جلسة",
    price:       null,
    priceNote:   "Minimum package: 4 sessions.",
    priceNoteAr: "الحد الأدنى للحزمة: 4 جلسات.",
    icon:        "◈",
    image:       "/services/majlis-fatayat.png",
    timeline: [
      { en: "Apply your personalised treatment plan", ar: "تطبيق خطة العلاج المخصصة لكِ" },
      { en: "Identify and interrupt negative thinking patterns", ar: "تحديد ومقاطعة أنماط التفكير السلبية" },
      { en: "Learn CBT tools for anxiety and emotional regulation", ar: "تعلّم أدوات العلاج السلوكي المعرفي للقلق والتنظيم العاطفي" },
      { en: "Build long-term resilience, not dependency on sessions", ar: "بناء مرونة طويلة المدى، وليس الاعتماد على الجلسات" },
      { en: "Track progress and adjust your plan as you grow", ar: "متابعة التقدم وتعديل الخطة مع تطوّرك" },
    ],
  },
  {
    id:          "prewedding",
    title:       "Pre-Wedding Psychological Preparation",
    titleAr:     "رحلة ما قبل الزفاف – إعداد نفسي عميق للحياة الزوجية",
    description: "A premium, invitation-only program for brides who want to enter married life with deep emotional clarity, healthy relationship patterns, and genuine inner readiness.",
    descriptionAr: "برنامج حصري للعرائس اللواتي يردن الدخول إلى الحياة الزوجية بوعي عاطفي عميق وأنماط علاقات صحية واستعداد نفسي حقيقي.",
    includes: [
      "8 individual sessions with the bride",
      "2 joint sessions with the groom",
      "CBT-based psychological guidance",
      "Supervision by Alia AlBahri",
    ],
    includesAr: [
      "8 جلسات فردية مع العروس",
      "جلستان مشتركتان مع العريس",
      "إرشاد نفسي مبني على العلاج المعرفي السلوكي",
      "إشراف من علياء البحري",
    ],
    format:      "Session-based program",
    formatAr:    "برنامج بالجلسات",
    duration:    "10 sessions total",
    durationAr:  "10 جلسات إجمالًا",
    price:       null,
    priceNote:   "Admission is selective. Apply by sending 'Ready' on WhatsApp.",
    priceNoteAr: "القبول انتقائي. للتقديم أرسلي «جاهزة» عبر واتساب.",
    icon:        "❋",
    image:       "/services/prewedding.png",
    timeline: [
      { en: "Analyse your emotional thinking patterns before entering the relationship", ar: "تحليل نمط التفكير العاطفي لديكِ قبل الدخول في العلاقة" },
      { en: "Understand yourself and your psychological needs deeply", ar: "فهم ذاتك واحتياجاتك النفسية بشكل أعمق" },
      { en: "Learn languages of communication and emotional influence", ar: "تعلّم لغات التواصل والتأثير العاطفي مع الشريك" },
      { en: "Win your partner's heart through understanding, not pressure", ar: "كسب قلب شريكك بالفهم والاحتواء لا بالضغط والسيطرة" },
      { en: "Manage marital conflicts with awareness, without escalation", ar: "إدارة الخلافات الزوجية بوعي دون تصعيد أو انسحاب" },
      { en: "Discover and correct cognitive distortions that affect relationships", ar: "اكتشاف وتصحيح التشوهات الفكرية التي قد تؤثر على العلاقة" },
      { en: "Build inner security and trust within the relationship", ar: "بناء شعور داخلي بالأمان والثقة داخل العلاقة" },
      { en: "Realistic psychological preparation for married life", ar: "الاستعداد النفسي الواقعي لمسؤوليات الحياة الزوجية" },
    ],
  },
  {
    id:          "adolescent",
    title:       "The Art of Dealing with an Adolescent",
    titleAr:     "فن التعامل مع المراهق",
    description: "A recorded course for mothers and parents who want to truly understand their adolescent, and become the calm, influential presence their child needs.",
    descriptionAr: "دورة مسجّلة للأمهات والآباء الذين يريدون فهم مراهقيهم حقًا، وأن يكونوا الحضور الهادئ والمؤثر الذي يحتاجه أبناؤهم.",
    includes: [
      "5 recorded sessions",
      "Listening and communication skills",
      "Discipline without conflict",
      "Building self-esteem in your adolescent",
    ],
    includesAr: [
      "5 جلسات مسجّلة",
      "مهارات الاستماع والتواصل",
      "انضباط بلا صراع",
      "بناء تقدير الذات لدى ابنكِ المراهق",
    ],
    format:      "Recorded course, links sent after payment",
    formatAr:    "دورة مسجّلة، يُرسل الرابط بعد الدفع",
    duration:    "Access for 15 days",
    durationAr:  "مدة الوصول 15 يومًا",
    price:       null,
    priceNote:   null,
    priceNoteAr: null,
    icon:        "◇",
    image:       "/services/adolescent.png",
    timeline: [
      { en: "Adolescence from an educational psychology perspective", ar: "المراهقة من منظور علم النفس التربوي" },
      { en: "The clash with your adolescent: causes and solutions", ar: "الصدام مع المراهق: أسبابه وعلاجه" },
      { en: "Core psychological needs and how to fulfil them properly", ar: "الحاجات النفسية الأساسية عند المراهق وطرق إشباعها الصحيحة" },
      { en: "How to be the psychologically healing parent", ar: "كيف أكون الأم المعالجة نفسياً لابنتي المراهقة" },
      { en: "Building balanced personality through psychological skills", ar: "المهارات النفسية التي تساهم في بناء شخصية متوازنة" },
      { en: "Encouragement that builds self-esteem and self-respect", ar: "مهارة التشجيع النفسي الذي يزيد من تقدير واحترام الذات" },
      { en: "How to have a successful, influential parental conversation", ar: "كيف أجري محادثة أبوية ناجحة ومؤثرة" },
      { en: "The art of listening to your adolescent", ar: "مهارة الإنصات للمراهق" },
      { en: "The skill of persuasion to change negative behaviour", ar: "مهارة إقناع المراهق وتغيير سلوكه السلبي" },
    ],
  },
  {
    id:            "red-eye",
    title:         "Red Eye Mechanism & Communication Program",
    titleAr:       "آلية العين الحمراء + لغات التواصل والتأثير",
    sensoryLine:   "When the love is still there, but the connection isn't",
    sensoryLineAr: "حين يبقى الحب، لكن يغيب التواصل",
    description:   "A proprietary psychological framework for navigating marriage challenges. Covers emotional neglect, rebuilding connection after discovered infidelity, understanding emotional cooling after years of marriage, reigniting the attraction phase, applying Gottman's conflict theory, understanding the emotional separation ('exit') phase of the marital cycle, and reviving true love through evidence-based psychological methods. Part of the Languages of Communication and Influence program.",
    descriptionAr: "إطار نفسي متخصص للتعامل مع تحديات الحياة الزوجية. يشمل: التعامل مع اللامبالاة والنقد المستمر، إعادة بناء العلاقة بعد اكتشاف علاقات غير مشروعة، فهم أسباب فتور المشاعر بعد سنوات الزواج، إعادة إشعال مرحلة الانجذاب، تطبيق نظرية غوتمان في مواجهة الخلافات، فهم مراحل الانفصال العاطفي في الدورة الزواجية، وإحياء مشاعر الحب الحقيقي بأساليب نفسية مؤثرة. ضمن برنامج لغات التواصل والتأثير.",
    includes: [
      "6 core recorded sessions",
      "Bonus course: Fundamentals of Family Stability",
      "8 sessions total including bonus",
    ],

    includesAr: [
      "6 جلسات مسجّلة أساسية",
      "دورة إضافية: أسس الاستقرار الأسري",
      "8 جلسات إجمالًا شاملة المكافأة",
    ],
    format:      "Recorded course, links sent after payment",
    formatAr:    "برنامج مسجّل، يُرسل الرابط بعد الدفع",
    duration:    "Access for 1 month",
    durationAr:  "مدة الوصول شهرًا",
    price:       null,
    priceNote:   null,
    priceNoteAr: null,

    icon:        "◇",
    image:       "/services/red-eye.png",
    timeline: [
      { en: "When he doesn't care and constantly criticises: how to respond", ar: "زوجي لا يهتم بي وينتقدني باستمرار، كيف أتعامل" },
      { en: "Dealing with emotional coolness after years of marriage", ar: "فتور المشاعر بعد سنوات من الزواج، لماذا وكيف" },
      { en: "Restoring feelings from the engagement phase: is it possible?", ar: "إعادة المشاعر كما كانت في مرحلة الخطوبة، هل هذا ممكن؟" },
      { en: "Gottman theory: developing skills for managing marital conflict", ar: "نظرية غوتمان: تطوير المهارات لمواجهة الخلافات الزوجية" },
      { en: "Understanding real love and refreshing it with psychological tools", ar: "التعرف على مشاعر الحب الحقيقي وإنعاشها بأساليب نفسية مؤثرة" },
      { en: "Bonus: Fundamentals of Family Stability course", ar: "هدية: دورة أسس الاستقرار الأسري" },
    ],
  },
  {
    id:          "smart-memory",
    badge:       "Most Popular",
    badgeAr:     "الأكثر طلباً",
    title:       "Excellence Journey: Smart Memory Course",
    titleAr:     "دورة رحلة التميز نحو الذاكرة الذكية",
    description: "A memory development course teaching activation skills and fast memorisation techniques, with daily exercises, personal supervision, and confidence-building psychological training.",
    descriptionAr: "دورة لتطوير الذاكرة تُعلّم مهارات التنشيط وتقنيات الحفظ السريع، مع تمارين يومية وإشراف شخصي وتدريب نفسي لبناء الثقة بالنفس.",
    includes: [
      "Memory activation training",
      "Daily exercises for approximately one month",
      "Supervision by Alia and her team",
      "Psychological training to build positivity and confidence",
    ],
    includesAr: [
      "تدريب على تنشيط الذاكرة",
      "تمارين يومية لمدة شهر تقريبًا",
      "إشراف من علياء وفريقها",
      "تدريب نفسي لبناء الإيجابية والثقة",
    ],
    format:      "Contact us for details",
    formatAr:    "تواصلي معنا للتفاصيل",
    duration:    "Approx. 1 month",
    durationAr:  "نحو شهر",
    price:       null,
    priceNote:   "Contact us for details.",
    priceNoteAr: "تواصلي معنا للتفاصيل.",
    icon:        "✦",
    image:       "/services/smart-memory.png",
    timeline: [
      { en: "Memory activation and fast memorisation techniques", ar: "تنشيط الذاكرة وتقنيات الحفظ السريع" },
      { en: "Fun daily exercises that stimulate and strengthen memory", ar: "تدريبات يومية ممتعة ومحفزة لتنشيط الذاكرة" },
      { en: "The proper stabilisation technique for what you memorise", ar: "طريقة التثبيت الصحيحة للمحفوظ" },
      { en: "Psychological lectures to build positivity and confidence", ar: "محاضرات نفسية ترفع الإيجابية والثقة بالنفس" },
      { en: "Direct supervision from Alia AlBahri and her team", ar: "إشراف مباشر من أ. علياء البحري وفريقها المتميز" },
    ],
  },
  {
    id:          "majlis-fatayat",
    badge:       "New",
    badgeAr:     "جديد",
    title:       "Majlis Al Fatayat",
    titleAr:     "مجلس الفتيات",
    description: "A safe space for girls aged 14 to 17 to grow more confident, aware, and balanced. Weekly online sessions over 4 months, inspired by CBT, covering self-confidence, emotional awareness, overthinking, and stronger family communication.",
    descriptionAr: "مساحة آمنة للفتيات من 14 إلى 17 سنة لبناء شخصية أكثر ثقة ووعيًا واتزانًا. لقاءات أسبوعية أونلاين على مدى 4 أشهر، مستوحاة من العلاج المعرفي السلوكي، نعمل فيها على الثقة بالنفس، وفهم المشاعر، والتفكير الزائد، وتحسين التواصل داخل الأسرة.",
    includes: [
      "Weekly online group sessions",
      "CBT-inspired practical exercises",
      "Self-confidence & emotional awareness",
      "Stronger communication within the family",
    ],
    includesAr: [
      "جلسات جماعية أسبوعية أونلاين",
      "تمارين عملية مستوحاة من العلاج المعرفي السلوكي",
      "الثقة بالنفس والوعي العاطفي",
      "تواصل أقوى داخل الأسرة",
    ],
    format:      "Online weekly sessions",
    formatAr:    "جلسات أسبوعية أونلاين",
    duration:    "4 months",
    durationAr:  "4 أشهر",
    price:       null,
    priceNote:   "For girls aged 14–17. Contact us to enrol.",
    priceNoteAr: "للفتيات من 14 إلى 17 سنة. تواصلي معنا للتسجيل.",
    icon:        "✿",
    image:       "/services/cbt-sessions.png",
    timeline: [
      { en: "A safe space to open up and feel truly heard", ar: "مساحة آمنة للتعبير والشعور بأنها مسموعة حقًا" },
      { en: "Build self-confidence and a clearer sense of self", ar: "بناء الثقة بالنفس ووضوح أكبر للذات" },
      { en: "Understand, name, and regulate emotions", ar: "فهم المشاعر وتسميتها وتنظيمها" },
      { en: "Quiet overthinking with practical CBT tools", ar: "تهدئة التفكير الزائد بأدوات سلوكية معرفية عملية" },
      { en: "Improve communication within the family", ar: "تحسين التواصل داخل الأسرة" },
    ],
  },
  {
    id:          "majlis-aliya",
    badge:       "Most Influential",
    badgeAr:     "الأكثر تأثيراً",
    title:       "Aliya's Majlis",
    titleAr:     "مجلس علياء",
    description: "A cognitive-behavioural group therapy program designed to help women understand themselves deeply and build a more reassured, balanced life. We work on cognitive distortions, emotional regulation, self-confidence, anxiety, overthinking, relationships, and personality patterns, through weekly interactive sessions in a safe, supportive space.",
    descriptionAr: "برنامج علاجي جماعي معرفي سلوكي، صُمم لمساعدة المرأة على فهم نفسها بعمق وبناء حياة أكثر طمأنينة واتزانًا. نعمل فيه على تشوهات التفكير، وتنظيم المشاعر، والثقة بالنفس، والقلق، والتفكير الزائد، والعلاقات، وأنماط الشخصية، من خلال لقاءات أسبوعية تفاعلية في مساحة آمنة وداعمة",
    includes: [
      "Weekly online sessions over four months",
      "Practical applications and exercises between sessions",
      "Cognitive Behavioural Therapy (CBT) tools",
      "Work on self-confidence and emotional regulation",
      "Managing anxiety, overthinking, and cognitive distortions",
      "Understanding personality patterns and their effect on relationships",
      "Healthy boundary-setting and self-assertion skills",
      "A small women's group to ensure quality follow-up",
    ],
    includesAr: [
      "لقاءات أسبوعية أونلاين لمدة أربعة أشهر.",
      "تطبيقات وتمارين عملية بين اللقاءات.",
      "أدوات من العلاج المعرفي السلوكي (CBT).",
      "العمل على الثقة بالنفس وتنظيم المشاعر.",
      "التعامل مع القلق والتفكير الزائد وتشوهات التفكير.",
      "فهم أنماط الشخصية وتأثيرها على العلاقات.",
      "مهارات وضع الحدود الصحية وتوكيد الذات.",
      "مجموعة نسائية محدودة العدد لضمان جودة المتابعة.",
    ],
    suitableForAr: [
      "فهم نفسك بصورة أعمق.",
      "بناء حياة أكثر اتزانًا وطمأنينة.",
      "اكتساب أدوات عملية تساعدك مدى الحياة.",
      "إحداث تغيير حقيقي ومستدام في صحتك النفسية",
    ],
    format:      "Online weekly sessions",
    formatAr:    "جلسات أسبوعية أونلاين",
    duration:    "4 months",
    durationAr:  "4 أشهر",
    price:       null,
    priceNote:   "A group program for women. Contact us to enrol.",
    priceNoteAr: "برنامج جماعي للنساء. تواصلي معنا للتسجيل.",
    icon:        "✿",
    image:       "/services/majlis-aliya.png",
    timeline: [
      { en: "A safe, supportive space to open up and be truly heard", ar: "مساحة آمنة وداعمة للتعبير والشعور بأنكِ مسموعة حقًا" },
      { en: "Understand yourself and your personality patterns", ar: "فهم نفسك وأنماط شخصيتك" },
      { en: "Regulate emotions and quiet overthinking with CBT tools", ar: "تنظيم المشاعر وتهدئة التفكير الزائد بأدوات العلاج المعرفي السلوكي" },
      { en: "Work through anxiety and cognitive distortions", ar: "التعامل مع القلق وتشوهات التفكير" },
      { en: "Set healthy boundaries and build self-assertion", ar: "وضع حدود صحية وبناء توكيد الذات" },
    ],
  },
  {
    id:            "corporate",
    title:         "Corporate & Government Solutions",
    titleAr:       "الحلول المؤسسية",
    offeringLabel:   "Corporate Services",
    offeringLabelAr: "خدمات المؤسسات",
    description:   "Specialised training and psychological programs designed for government entities and companies — enhancing mental health, elevating human and leadership skills, and helping build more aware, productive, and sustainable workplaces.",
    descriptionAr: "برامج تدريبية ونفسية متخصصة مصممة للجهات الحكومية والشركات، تعزز الصحة النفسية، وترتقي بالمهارات الإنسانية والقيادية، وتسهم في بناء بيئات عمل أكثر وعياً وإنتاجية واستدامة.",
    disclaimer:    "This service is exclusively for companies and government entities.",
    disclaimerAr:  "هذه الخدمة مخصصة حصرياً للشركات والجهات الحكومية.",
    includes: [
      "Programs tailored to the organisation's needs",
      "Interactive lectures and workshops",
      "In-person or online",
      "For government entities and companies",
      "Measurable impact",
    ],
    includesAr: [
      "برامج مصممة حسب احتياج الجهة",
      "محاضرات وورش تفاعلية",
      "حضورياً أو أونلاين",
      "للجهات الحكومية والشركات",
      "أثر قابل للقياس",
    ],
    format:      "In-person or online",
    formatAr:    "حضورياً أو أونلاين",
    duration:    "Custom programs",
    durationAr:  "برامج مخصصة",
    price:       null,
    priceNote:   "For government entities and companies. Book an introductory meeting for details.",
    priceNoteAr: "للجهات الحكومية والشركات. احجز اجتماعاً تعريفياً للتفاصيل.",
    bookLabel:   "Book an Introductory Meeting",
    bookLabelAr: "احجز اجتماعاً تعريفياً",
    icon:        "❖",
    image:       "/services/corporate.png",
    timeline: [
      { en: "Workplace mental health programs — enhancing wellbeing, reducing stress, and supporting employees.", ar: "برامج الصحة النفسية في بيئة العمل — برامج تعزز الصحة النفسية، تقلّل الضغوط، وتدعم الرفاه النفسي للموظفين." },
      { en: "Emotional intelligence — developing EQ skills to improve communication, relationships, and successful teams.", ar: "الذكاء العاطفي — تطوير مهارات الذكاء العاطفي لتحسين التواصل والعلاقات وبناء فرق عمل ناجحة." },
      { en: "Stress management — practical programs to understand and manage stress and maintain balance.", ar: "إدارة الضغوط — برامج عملية تساعد على فهم الضغوط وإدارتها والمحافظة على التوازن النفسي." },
      { en: "Leadership development — specialised programs for leadership skills, team building, decision-making, and human-centred leadership.", ar: "تطوير القيادات — برامج متخصصة لتنمية مهارات القيادة وبناء الفرق واتخاذ القرار والقيادة الإنسانية." },
      { en: "Awareness talks — inspiring lectures for events, conferences, international days, and internal initiatives.", ar: "المحاضرات التوعوية — محاضرات ملهمة تناسب الفعاليات والمؤتمرات والأيام العالمية والمبادرات الداخلية." },
      { en: "Training workshops — interactive, applied workshops that turn knowledge into tangible skills.", ar: "الورش التدريبية — ورش تفاعلية تطبيقية لتحويل المعرفة إلى مهارات ملموسة في العمل والحياة." },
      { en: "Tailored programs — designed to fit the organisation's goals, culture, and target audience.", ar: "برامج مخصصة حسب احتياجات الجهة — تصميم البرامج بما يتناسب مع أهداف المؤسسة وثقافتها والفئة المستهدفة." },
      { en: "In-person or online — flexible delivery on-site or remotely via digital platforms.", ar: "حضورياً أو أونلاين — مرونة في تقديم البرامج داخل المؤسسة أو عن بُعد عبر المنصات الرقمية." },
      { en: "Follow-up & impact evaluation — final reports and recommendations to sustain impact and measure results.", ar: "متابعة وتقييم الأثر — تقارير ختامية وتوصيات لضمان استدامة التأثير وقياس النتائج." },
    ],
  },
] as const;

// ─── Service display order ────────────────────────────────────────────────────
// Single source of truth for the order services appear in across the site
// (home grid, services offerings, and the journey-detail timeline).
export const serviceOrder = [
  "consultation",
  "cbt-sessions",
  "majlis-aliya",
  "smart-memory",
  "majlis-fatayat",
  "prewedding",
  "adolescent",
  "red-eye",
  "corporate",
] as const;

export const orderedServices = serviceOrder
  .map((id) => services.find((s) => s.id === id))
  .filter((s): s is (typeof services)[number] => Boolean(s));

// ─── Testimonials ─────────────────────────────────────────────────────────────
// Four verified bilingual testimonials. Names reduced to initials in both
// locales. Testimonial 2 (M. A.) is the emotional climax — `featured: true`.

export const testimonials = [
  {
    id: "t1",
    name: "N. H.",
    nameAr: "طبيبة وأم لطفلين - أبوظبي",
    quote: "I personally gained great benefit. I applied many of the techniques and methods I learned — in my own home — and the results were astonishing. The impact exceeded what I had expected for myself. I strongly urge every woman to attend this course, to be fully present in it, and to practice what it teaches.",
    quoteAr: "بصراحة كنت أقول مستحيل أتغير. اليوم أقدر أقول إني مرتاحة أكثر من أي وقت مضى، وأحس إني أقرب لنفسي ولأطفالي من زمان",
    rating: 5,
    image: null,
    featured: false,
  },
  {
    id: "t2",
    name: "M. A.",
    nameAr: "كاتبة - مسقط",
    quote: "My pen fails to find the words to thank you for this course, which lit the lamps of my heart and the lamps of my home. Praise be to God — I now live, after this course, in a state of calm and stillness in my home. I used to search through my husband's phone constantly, and I could not hold myself back. Whenever something troubled me inside, I would carry that pressure and that tension onto my children. Glory to God — your course, your elegance, your femininity showed me exactly what I want. I learned, precisely, what my husband needs and what my children need. I have become able to treat them with all the beautiful techniques you taught us. And by God, from a heart that loves you dearly — thank you, thank you, thank you.",
    quoteAr: "ما كنت متوقعة إني أستفيد بهالشكل. أحس إني صرت أفهم نفسي أكثر وأتعامل مع مشاعري بهدوء ووعي. حتى نظرتي للحياة تغيرت بشكل جميل.",
    rating: 5,
    image: null,
    featured: false,
  },
  {
    id: "t3",
    name: "F. S.",
    nameAr: "سيدة أعمال - دبي",
    quote: "My feeling… deeply, deeply happy. I used to feel that the surahs of the Qur'an were distant from me, that reaching each surah required a long journey. Now I feel that all the surahs are before me at once. I also feel a quiet intimacy between my hands and the Qur'an — the opposite of what I felt before this beautiful course, all praise to God. I thank you all, and may God weigh this in your good deeds. May God bring benefit to Islam and to all Muslims through you, O Lord.",
    quoteAr: "أكثر شيء فرق معي إني صرت أعيش براحة نفسية أكبر. الأشياء اللي كانت تستنزفني نفسيًا ما عادت تأثر فيني مثل قبل.",
    rating: 5,
    image: null,
    featured: true,
  },
  {
    id: "t4",
    name: "A. K.",
    nameAr: "أم لثلاثة أبناء - الرياض",
    quote: "I created this group because of the benefit I have seen God bring through the hand of Professor Aliyah Al Bahari — may God preserve her. In short: chaos has spread in our time due to speakers on upbringing and psychology who have no evidence and no grounding in sacred law. And with the need for true, researched knowledge in this field that aligns with the Sharia — I found this in Doctor Aliyah. She has combined academic study with a full ijaza in the Noble Qur'an. Far from the pretenders who attend a few courses in presentation skills and the art of delivery and persuasion and then declare themselves trainers.",
    quoteAr: "كنت أحس إني تايهة ومشتتة وما أعرف من وين أبدأ. اليوم عندي وضوح أكثر، وصرت أعرف كيف أتعامل مع نفسي ومع اللي أمر فيه.",
    rating: 5,
    image: null,
    featured: false,
  },
  {
    // No 5th English testimonial was provided. Per the "Arabic-only" choice, the
    // English field mirrors the Arabic for now — replace with English when available.
    id: "t5",
    name: "معلمة - الكويت",
    nameAr: "معلمة - الكويت",
    quote: "اللي تغير مو ظروفي، اللي تغير إني أنا تغيرت. صرت أهدى وألطف مع نفسي، وأستمتع بتفاصيل حياتي أكثر.",
    quoteAr: "اللي تغير مو ظروفي، اللي تغير إني أنا تغيرت. صرت أهدى وألطف مع نفسي، وأستمتع بتفاصيل حياتي أكثر.",
    rating: 5,
    image: null,
    featured: false,
  },
] as const;
